### ISSUE TITLE
ehrQL imports display syntax errors in VS Code

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/research-template-docker#19]
The ehrQL imports in opensafely/research-template `analysis/dataset_definition.py` display syntax errors in VS Code. However, other imports (e.g. `import pandas`) don't.

**Comment by Jongmassey** [comment]
I can't replicate this - can you detail steps to reproduce?

**Comment by Jongmassey** [comment]
![Image](https://github.com/opensafely-core/research-template-docker/assets/25795240/3dbd4b62-5f2c-432d-9d4c-5ca1a6e94433)


Here's a fresh codespace on that branch

**Comment by iaindillingham** [comment]
Ah! My apologies, the blue squiggly lines aren't syntax errors. They're spelling errors. I installed the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension, and Codespaces is smart enough to use that in VS Code in the browser as well as on the desktop.

<img width="1552" alt="improve-devcontainers-vs-code" src="https://github.com/opensafely-core/research-template-docker/assets/477263/84c32ff1-3166-4dc0-b833-5ead3c2424da">
