### ISSUE TITLE
The Python venv isn't activated in VS Code's Terminal

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/research-template-docker#20]
This means tools such as `ipython` and `pytest` aren't available. The user can run:

```sh
source /opt/venv/bin/activate
```

However, the user would need to know where the venv was located and what a venv was.

**Comment by Jongmassey** [comment]
I can't replicate this - can you detail steps to reproduce?

**Comment by Jongmassey** [comment]
Typo in now fixed in [this commit](https://github.com/opensafely/research-template/pull/120/commits/289de8fa495ed391463f9718ac8f48a07bf45137) - venv now activates once the python extension has activated

**Comment by Jongmassey** [comment]
What's extensiondisable doing? Is this codespace in a browser or connected to from locally installed vs code?

**Comment by Jongmassey** [comment]
![image](https://github.com/opensafely-core/research-template-docker/assets/25795240/7ee35aef-a182-4adf-ba7c-7553e3bec067)
In browser is working for me

**Comment by Jongmassey** [comment]
The terminal that starts upon codespace startup (the one that starts rstudio server) shows this message for me
![image](https://github.com/opensafely-core/research-template-docker/assets/25795240/4b25a742-29d3-4c79-918a-1d0886ff4e0d)

Any terminals manually created have the venv activated. 

Is there anything in the output/python pane? I wonder if your local extensions/config are interfering with the codespaces config?

**Comment by Jongmassey** [comment]
I think there's some weird interactions with local extensions/settings when opening a codespace in VS code rather than in a browser. In any case, it can take a while for the Python extension to activate. We could add a venv activation statement to the `postAttachCommand` following the start of RStudio Server such that the already-open terminal immediately has an activated venv

**Comment by Jongmassey** [comment]
Some further observations:

* The Python extension is not activated on startup, only on opening a `.py` file
* Therefore any terminals opened before its activation may not have a venv activated
* The initial shell presented to the user is opened `onAttach` (to start rstudio) which is before extension activation and thus doesn't have the venv activated
* The user may not notice the warning triangle in the terminals pane to show the terminal needs to be reloaded to start the venv

Also:
* It's not possible to force activation of an extension on startup. An extension's `package.json` defines its startup events, and in the case of the Python one it doesn't have application startup as one of them
* Automatically opening a Python file on vs code startup would do the trick but that's an undesirable hack for a whole host of reasons

Therefore:

I propose we add a venv activation statement to the `rstudio` user's `.bashrc` as part of the Dockerfile
