### ISSUE TITLE
Move postAttach and postCreate actions to Dockerfile

### ISSUE THREAD

**Issue by Jongmassey** [opensafely-core/research-template-docker#29]
The research template `devcontainer.json`  contains a `postCreateCommand` [setting](https://github.com/opensafely/research-template/blob/bc24007b959b226bd7cc3a199252907de05148e1/.devcontainer/devcontainer.json#L16) and `postAttachCommand` [setting](https://github.com/opensafely/research-template/blob/bc24007b959b226bd7cc3a199252907de05148e1/.devcontainer/devcontainer.json#L17-L19). Currently the former calls `.devcontainer/postCreate.sh` (which is included in the research template repo), and the latter starts rstudio server.

If we wish to make changes to what happens on either of these events, then this currently requires making changes to the research template which:
* is harder to deploy to all users
* is harder to test that concurrent changes to the Dockerfile and `devcontainer.json` work correctly together

I propose that:
* `postCreate.sh`, `requirements.in` and a new `postAttach.sh` are added to the image as part of the Dockerfile
* the `devcontainer.json` `postCreateCommand` and `postAttachCommand` settings call these scripts.
* `postcreate.sh` and `requirements.in` are removed from the research template repository

## Acceptance criteria
* The postAttach and postCreate scripts are moved as described above
* Documentation is updated for adding a Codespace to an existing project
* There's an upgrade path for existing Codespaces users. 

Note: we should keep an eye on how long this work takes and maybe reconsider if it potentially takes us beyond 28th June.

**Comment by StevenMaude** [comment]
- [ ] #57
- [ ] https://github.com/opensafely/research-template/pull/137

**Comment by StevenMaude** [comment]
Closing as the related PRs are now merged.
