### ISSUE TITLE
Error when attempting to load the `tidyverse` package

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/research-template-docker#31]
@alschaffer reports the following error when attempting to load the `tidyverse` package in RStudio:

```r
> library("tidyverse")
Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/xml2/libs/xml2.so':
  libxml2.so.2: cannot open shared object file: No such file or directory
In addition: Warning messages:
1: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘tibble’ 
2: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘tibble’ 
3: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘tibble’ 
4: replacing previous import ‘ellipsis::check_dots_unnamed’ by ‘rlang::check_dots_unnamed’ when loading ‘pillar’ 
5: replacing previous import ‘ellipsis::check_dots_used’ by ‘rlang::check_dots_used’ when loading ‘pillar’ 
6: replacing previous import ‘ellipsis::check_dots_empty’ by ‘rlang::check_dots_empty’ when loading ‘pillar’ 
```

Andrea started a Codespace from [opensafely/waiting-list](https://github.com/opensafely/waiting-list). I was able to recreate the above error in a new Codespace started from opensafely/research-template.[^1] I successfully loaded several other packages from [`packages.csv`](https://github.com/opensafely-core/r-docker/blob/main/packages.csv).

[^1]: `bc24007b959b226bd7cc3a199252907de05148e1`

**Comment by StevenMaude** [comment]
In the OpenSAFELY R image, `libxml2` is installed as a system package. Testing inside that R image, if you `apt remove libxml2`, you get the same error inside that R image:

```
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/renv/lib/R-4.0/x86_64-pc-linux-gnu/xml2/libs/xml2.so':
  libxml2.so.2: cannot open shared object file: No such file or directory
```

**Comment by StevenMaude** [comment]
Additional dependencies for the R Docker image in:

https://github.com/opensafely-core/r-docker/blob/bb8e0325c84f7b606124bf7294d5e4a5fda2681c/build-dependencies.txt
https://github.com/opensafely-core/r-docker/blob/bb8e0325c84f7b606124bf7294d5e4a5fda2681c/dependencies.txt

**Comment by Jongmassey** [comment]
I'm not sure we need the build dependencies as we're not building any of these packages from source. The omission of the dependencies is definitely an error. 

I suppose if we want to support user installation of R packages from source then we might need those build dependencies. However, there may be additional dependencies for packages we don't know about.

**Comment by Jongmassey** [comment]
Importing all packages:

```r
ip = unique(as.list(as.data.frame(installed.packages()[,c(1)])))
for (i in ip[[1]]){
  eval(parse(text=paste("library(\"",i,"\")",sep="")))
}
```
shows other missing dependencies:
* `brms`  - `libnode64`
* `magick`  - `libmagick++-6.q16-8` 
* `odbc` - `unixodbc-dev` *
* `rgdal` - `libgdal-dev`  * 
* `sf` - `libudunits2-0` 
* `tcltk` - `libtcl8.6` and `libtcl8.6` **

Which are in [dependencies.txt](https://github.com/opensafely-core/r-docker/blob/main/dependencies.txt) or [build-dependencies.txt](https://github.com/opensafely-core/r-docker/blob/main/build-dependencies.txt) (*). `libtcl` and `libtk` (**) are odd ones, not in either dependencies file, but feature in [20.04-library-changes.txt](https://github.com/search?q=repo%3Aopensafely-core%2Fr-docker%20libtcl&type=code)

**Comment by Jongmassey** [comment]
AFAICT assessing only direct dependencies:
[brms isn't used](https://github.com/search?q=org%3Aopensafely+brms+language%3AR+&type=code)
[magick is](https://github.com/search?q=org%3Aopensafely+magick+language%3AR+&type=code)
[odbc is, but only for the high cost drugs dataset](https://github.com/search?q=org%3Aopensafely+odbc+language%3AR+&type=code)
[rgdal isn't used](https://github.com/search?q=org%3Aopensafely+rgdal+language%3AR+&type=code)
[sf is used](https://github.com/search?q=org%3Aopensafely+sf+language%3AR+&type=code)
[tcltk isn't used](https://github.com/search?q=org%3Aopensafely+tcltk+language%3AR+&type=code)


Maybe in addition to `libxml2` we should also install `libmagick++` and `libudunits` to support existing researcher code?
