### ISSUE TITLE
Inconsistent return values from `here::here()`

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/research-template-docker#62]
@rose-higgins reports that R's `here::here()` function works differently in a Codespaces R environment than in a local R environment.[^1] Whilst Rose and Will think the difference is likely because of a version mis-match, it would be useful to know whether [the code Rose was updating][1] was never intended to be executed within our R action image.

Timebox to 1-2 hours.

[^1]: https://bennettoxford.slack.com/archives/C33TWNQ1J/p1714563093617839

[1]: https://github.com/opensafely/antibody-and-antiviral-deployment/blob/6136fa43cd923a38e5fec06ec5ca966700c3d89a/reports/coverage/mabs_and_antivirals_coverage_report.Rmd#L51

**Comment by Jongmassey** [comment]
>it would be useful to know whether [the code Rose was updating](https://github.com/opensafely/antibody-and-antiviral-deployment/blob/6136fa43cd923a38e5fec06ec5ca966700c3d89a/reports/coverage/mabs_and_antivirals_coverage_report.Rmd#L51) was never intended to be executed within our R action image.

AFAICT that Rmd file doesn't appear anywhere in project.yaml

**Comment by iaindillingham** [comment]
Thanks for looking into this, @Jongmassey. I'm going to close because I don't think the code Rose was updating was ever intended to be executed within our R action image.

**Comment by iaindillingham** [comment]
`here` (the package) is at [v0.1 on the R action image](https://github.com/opensafely-core/r-docker/blob/bb8e0325c84f7b606124bf7294d5e4a5fda2681c/packages.csv#L161), but [v1.0.1 on CRAN](https://cran.r-project.org/web/packages/here/index.html).

**Comment by Jongmassey** [comment]
[2017](https://github.com/r-lib/here/releases/tag/v0.1)-old
