### ISSUE TITLE
Change Codespaces timeout

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/research-template-docker#68]
A researcher recently [lost some of their work](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1728297387260449) because their Codespace was deleted. They stopped working on the project for two weeks and didn't receive any notification from GitHub that it was about to be deleted.

We should review the current two week limit and replace it with something that means researchers are less likely to lose work. For example, we could have no limit and have a manual process instead (possibly with bennettbot's help).

We should also communicate and document any changes to this policy, both in the team manual and the opensafely docs.

**Comment by lucyb** [comment]
Timeout changed to sixty days.

TODO

- [ ] Update OS docs
- [ ] Update team manual
- [ ] Communicate change (new codespaces only)

**Comment by iaindillingham** [comment]
This was marked as "Done", but not closed. Happens! Lucy also comminicated the change in [#opensafely](https://bennettoxford.slack.com/archives/C010SJ89SA3/p1728401051524209) and [#opensafely-users](https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1728401048033609).
