### ISSUE TITLE
Codespaces: Identify researchers whose Codespaces are at risk of deletion

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/research-template-docker#70]
We should 

* Identify researchers whose Codespaces are at risk of deletion
* Make this list available to Team REX (ideally in Slack, where we'll see it)
* Inform the researchers
* Find out why the Codespace was inactive and whether they would have lost any work. Record the findings.

**Comment by iaindillingham** [comment]
We're going to keep this ticket in Awaiting Triage, pending the "Codespaces - What to measure?" meeting on Tuesday 15th October.

**Comment by iaindillingham** [comment]
A rough-and-ready means of identifying Codespaces at risk of deletion is...

```sh
#!/usr/bin/env bash

gh codespace list \
    --org opensafely \
    --json gitStatus,lastUsedAt,owner,repository |
    jq '.[] | select(.repository != "opensafely/research-template" and (.gitStatus.hasUncommittedChanges or .gitStatus.hasUnpushedChanges)) | {lastUsedAt: .lastUsedAt, owner: .owner, repository: .repository}'
```

You need to be an owner of the opensafely org, and to have `gh` and `jq`.

**Comment by Jongmassey** [comment]
Part 1: [Get the required data from the GitHub API into the metrics db](https://github.com/ebmdatalab/metrics/pull/254)
Part 2: (TODO) Add a dashboard to Grafana to display codespaces that have uncommitted or un-pushed changes and are close to 30d since last activity

**Comment by Jongmassey** [comment]
Let's do this in Bennett Bot - doing this in metrics would open some cans of worms we don't want to address right now
