### ISSUE TITLE
Codespaces: Attend LSHTM meeting

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/research-template-docker#71]
After an LSHTM researcher experienced a problem using a Codespace recently, we realised that we hadn't formally introduced Codespaces to them. Given that our documentation is not fully comprehensive and even if it could be then it's still possible to miss information, we think it would be worthwhile attending one of LSHTM's regular OpenSAFELY meetings. 

In the meeting, we should:
* Ensure they're aware of how Codespaces works and its limitations
* Try to understand a bit more about how they're using Codespaces and any other problems they may have had

**Comment by iaindillingham** [comment]
Attended! We emphasised

* that currently Codespaces are auto-deleted after 30 days of inactivity. However, we are working on this #78 and #70.
* that it's important to save, commit, _and push_ changes.

Ed, who chaired the meeting, was very pleased that a Codespaces comes with the versions of the R packages that are in the R image. Version mismatch headaches are unpleasant.
