### ISSUE TITLE
Codespaces: Codespace is slow to respond

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/research-template-docker#77]
Will created a Codespace that is slow to respond ("very very laggy"). He reported this to tech support, alongside several other issues with the Codespace.[^1]

Will, @Mary-Anya, and @iaindillingham are meeting on Thursday 24th October to find out more about this issue, and the related issues. One outcome will be to gather more information about what "slow to respond" means, as well as contextual information about VPNs, upload/download speeds, etc.

[^1]: https://bennettoxford.slack.com/archives/C33TWNQ1J/p1729177307365829

**Comment by iaindillingham** [comment]
CCing @sebbacon.

**Comment by iaindillingham** [comment]
Will has worked with Codespaces at his home and in the office. Will has described his home's connectivity as "poor" and the office's connectivity as "good".

**Comment by iaindillingham** [comment]
Will reports that he has a download speed of 30Mbps and an upload speed of 3Mbps at home.[^1] The upload speed seems slow; for comparison, mine is 19.2/7.51. He's going to try in the office, the next time he's in the office.

[^1]: https://bennettoxford.slack.com/archives/C33TWNQ1J/p1729801229312559?thread_ts=1729177307.365829&cid=C33TWNQ1J

**Comment by lucyb** [comment]
I'm moving this to blocked, until Will tries out his new `chilling-spooky-spirit` Codespace in the office.

**Comment by lucyb** [comment]
It's past halloween, but Will has tried running `chilling-spooky-spirit` in the office. He's [said](https://bennettoxford.slack.com/archives/C33TWNQ1J/p1730901496112609?thread_ts=1729177307.365829&cid=C33TWNQ1J):

> i'm trying now on my v old laptop. It opens up fine. No repeat of issues I had before. [...] It occasionally freezes but i think that's the laptop!

Given this, I'm going to close this issue as I don't think we need to take any further action. However, I have recommended that Will look into getting a new laptop (home internet issues aside, it sounds like it's often too slow).
